# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fadc31a10939b9f81ee81a6b3a9fdfcdd407b80c823070d0a170175912fc625b528c212a16684c09a2737781d1e4c2a2247490b5802419dffa1a70c2e5a105b

test:
  secret_key_base: c447abb017c83dd533058fa4765687d29633f2fc9bb1e3cdf3276eb7b870385bc4b5248046245aade343b33f694df60f08de025609276624c0a2039088686100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
